### ISSUE TITLE
forceSafeTransferETH

### ISSUE THREAD

**Issue by martinmtm** [ethscriptions-protocol/Bug-Competition#2]
Upon reviewing the code more carefully, I have identified a potential bug in the forceSafeTransferETH function.

if iszero(
    and( // The arguments of `and` are evaluated from right to left.
        // Set success to whether the call reverted, if not we check it either
        // returned exactly 1 (can't just be non-zero data), or had no return data.
        or(eq(mload(0x00), 1), iszero(returndatasize())),
        call(gas(), token, 0, 0x1c, 0x64, 0x00, 0x20)
    )
) {
    mstore(0x00, to) // Store the address in scratch space.
    mstore8(0x0b, 0x73) // Opcode `PUSH20`.
    mstore8(0x20, 0xff) // Opcode `SELFDESTRUCT`.
    // We can directly use `SELFDESTRUCT` in the contract creation.
    // Compatible with `SENDALL`: https://eips.ethereum.org/EIPS/eip-4758
    if iszero(create(amount, 0x0b, 0x16)) {
        // To coerce gas estimation to provide enough gas for the `create` above.
        if iszero(gt(gas(), 1000000)) { revert(0, 0) }
    }
}

The issue lies in the create function call inside the conditional block. The create function creates a new contract with the given bytecode. In this case, the amount is used as the bytecode to create the contract. This is potentially problematic because amount is the value of the ETH to be transferred, and it's being used as the bytecode for contract creation.

The create function call should not use amount as the bytecode, as it may lead to unintended behavior or security vulnerabilities. It should use proper bytecode to create the contract instead.

**Comment by RogerPodacter** [comment]
Thanks for this! I'm asking that library's creator, the immortal @Vectorized!

**Comment by Vectorized** [comment]
The `create` opcode includes a parameter to send `amount` ETH upon contract creation. 

See http://evm.codes for more details.
