### ISSUE TITLE
A discussion about using composition or inheritance

### ISSUE THREAD

**Issue by toshtoss** [ethscriptions-protocol/Bug-Competition#4]
I believe the relationship between EthscriptionsEscrower.sol and EthscriptionsMarketV3.sol should be one of composition rather than inheritance. This is because our indexer can only listen to the ethscriptions_protocol_TransferEthscriptionForPreviousOwner event emitted by specific contracts. Therefore, if we want to allow third-party developers to develop their own market contracts, we should consider using composition.

**Comment by RogerPodacter** [comment]
Interesting! How would composition work in this case? We could make the
escrower a library instead of a base contract, is that what you have in
mind?

**Comment by BSCNFTs** [comment]
Composition could be advantageous in your scenario:

Event Listening: As mentioned, your indexer can only listen to events emitted by specific contracts. By using composition, the EthscriptionsMarketV3.sol contract can include an instance of EthscriptionsEscrower.sol and directly listen to its events without the need for inheritance. This decouples the two contracts, allowing you to use the market contract with different escrow contracts if needed.

Flexibility: Composition provides more flexibility than inheritance. If you use inheritance, the two contracts would be tightly coupled, and you might face limitations when trying to change or update the functionality of one contract independently of the other. With composition, you can easily switch or upgrade the escrow contract without affecting the market contract.

Third-party Development: By using composition, you can enable third-party developers to develop their own market contracts that can interact with different escrow contracts. This way, developers can create their custom market contracts while using various escrow contracts based on their specific use cases.

**Comment by RogerPodacter** [comment]
Thanks to all who participated! After reviewing all the submissions and testing the marketplace for more than a month, we have concluded that no one was eligible for a prize. However we do appreciate all submissions!
